on:
  push:
    branches:
      - master
jobs:
  release-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4.1.0
      - name: Build
        timeout-minutes: 25
        run: ./gradlew check
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify -s src/website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          personal_token: ${{ secrets.PUBLIC_TOKEN }}
          external_repository: http4k/www.http4k.org
          publish_branch: main
          publish_dir: src/website/public
          cname: new.http4k.org


      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12.0'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: ./tools/embed_code.py
      - uses: actions/checkout@v4.1.7
        with:
          repository: http4k/www.http4k.org
          path: tmp
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
      - run: cp -R build/docs-website/docs tmp/
      - run: cp -R src/mkdocs.yml tmp/
      - run: pushd tmp && mkdocs gh-deploy && popd

