name: Update Website
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  release-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4.1.0
      - name: Build
        timeout-minutes: 25
        run: ./gradlew check
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.10.2'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - run: ./tools/embed_code.py
      - uses: actions/checkout@v4.1.7
        with:
          repository: http4k/www.http4k.org
          path: tmp
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
      - run: cp -R build/docs-website/docs tmp/
      - run: cp -R src/mkdocs.yml tmp/
      - run: pushd tmp && mkdocs gh-deploy && popd

