on:
  repository_dispatch:
    types: [http4k-connect-release]
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
         ./upgrade_http4k_connect.sh ${{ github.event.client_payload.version }}
          git commit -am "Upgrade http4k"
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
