on:
  repository_dispatch:
    types: [http4k-release]
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
         git config --local user.name "github-actions"
         git config --local user.email "github-actions@github.com"
         ./upgrade_http4k.sh ${{ github.event.client_payload.version }}
         git add .
         git commit -am "Upgrade http4k"
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
